// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB27ZjOMWjdCg9VQ1l2LAJXe1HGhHLPxeU',
    appId: '1:572757838694:web:9e385c974c3ed8097916a7',
    messagingSenderId: '572757838694',
    projectId: 'flutter-app-007',
    authDomain: 'flutter-app-007.firebaseapp.com',
    storageBucket: 'flutter-app-007.appspot.com',
    measurementId: 'G-YJQK9CTV1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz8CgqzmRUlrplWAV-dKYCbWHjomVZ920',
    appId: '1:572757838694:android:21d1256b017275a27916a7',
    messagingSenderId: '572757838694',
    projectId: 'flutter-app-007',
    storageBucket: 'flutter-app-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYN5nQUlNDFB6zRMt5mRePxAYl2dYVOxc',
    appId: '1:572757838694:ios:6995ccdc4e00b0057916a7',
    messagingSenderId: '572757838694',
    projectId: 'flutter-app-007',
    storageBucket: 'flutter-app-007.appspot.com',
    iosClientId: '572757838694-ir2rdn134hc3bdcmrg5v1dn5omkanec8.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceApp',
  );
}
